### ISSUE TITLE
New webwork 2.15 server canvas LTI integration configuration.

### ISSUE THREAD

**Issue by jeis4wpi** [openwebwork/docs#17]
Hi All,

Not sure what I have that is wrong but my authen_LTI.conf looks like:
```
grep -Ev "^#" authen_LTI.conf


$debug_lti_parameters = 1; 

$debug_lti_grade_passback = 1;


$authen{user_module} = [ 
	{  "*" => "WeBWorK::Authen::LTIAdvanced", }, #preferred authorization method
	{  "*" => "WeBWorK::Authen::Basic_TheLastOption",}  #fallback authorization method
];



$external_auth=0;

$preferred_source_of_username = "lis_person_contact_email_primary";


$strip_address_from_email = 1;


$LTIBasicConsumerSecret = "LKJLKJLJ"; # OK per my canvas admin

$NonceLifeTime=60; # in seconds


$LMSManageUserData=1;

$LTIGradeOnSubmit = 1;

$LTIMassUpdateInterval = 86400; #in seconds

%LMSrolesToWeBWorKroles = (
			   "librarian" => "guest",
			   "observer" => "guest",
			   "visitor" => "guest",
			   "Guest"  => "guest",
			   "Designer" => "professor",
			   "instructor" => "professor",
			   "Instructor" => "professor",
			   "Faculty" => "professor",
			   "Teacher" => "professor",
			   "Student" => "student",
			   "Learner" => "student",
			   "student" => "student",
			   "AI/TA" => "ta",
			   "TA" => "ta",
			   "Teaching Assistant" => "ta",
			   "Teaching Assistant (TA)" => "ta",
			   "Non-editing teacher" => "ta",
			   "Grader" => "ta",
    );


$LTIAccountCreationCutoff = "ta";

$LTI_modify_user = sub {
  # The self object from LTIAdvanced.pm
  my $self = shift;
  # The user object to be modified
  my $user = shift;

  # Parse context_id for additional information.  E.G.  
  my @course_id=split /-/, $self -> {"context_id"};
  $user->{"section"} = $course_id[4];

  };

1; #final line of the file to reassure perl that it was read properly.

```

and the local settings:

include("conf/authen_LTI.conf");
$debug_lti_parameters = 1;
$debug_lti_grade_passback = 1;
include("conf/authen_CAS.conf");

has the include for authen_LTI.conf but the debug and course logs never show LTI activity ?  How can I debug my LTI integration issues with Canvas?

Thank you.

**Comment by dlglin** [comment]
These types of questions are better served by the forums (https://webwork.maa.org/forums).

Based on what you included, it sounds like you have a similar issue to one described in https://webwork.maa.org/moodle/mod/forum/discuss.php?d=4971

You are including two different conf files for authentication.  Most likely each of them has a directive listing which authentication modules to enable.  Since conf/authen_CAS.conf is loaded last, that one will take precedence.  You will likely need to add something like the following in either authen_CAS.conf or in localOverrides.conf after both include statements:
$authen{user_module} = [ 
	{  "*" => "WeBWorK::Authen::LTIAdvanced", }, #preferred authorization method
        {  "*" => "WeBWorK::Authen::CAS", }
	{  "*" => "WeBWorK::Authen::Basic_TheLastOption",}  #fallback authorization method
];

You need this to enable both LTI and CAS authentication.

**Comment by jeis4wpi** [comment]
That helps me alot.  I will now ask students to test for me.

**Comment by jeis4wpi** [comment]
Is there a difference between "*" vs "" ?

```shell

include("conf/authen_LTI.conf");
$debug_lti_parameters = 1;
$debug_lti_grade_passback = 1;
#-->$LTIGrademode="homework";
include("conf/authen_CAS.conf");

 $authen{user_module} = [
{ "*" => "WeBWorK::Authen::LTIAdvanced", }, #preferred authorization method
{ "*" => "WeBWorK::Authen::CAS", },
{ "*" => "WeBWorK::Authen::Basic_TheLastOption",} #fallback authorization method
];
```

from the localOverrides.conf has students working from canvas to webwork.

Thank you again!

**Comment by dlglin** [comment]
There should be stars in each of those.  They probably got lost in my copy and paste.

**Comment by jeis4wpi** [comment]
Thank you again Danny for your help and the clarity regarding the stars.
